image: node:12

variables:
  DOCKER_DRIVER: overlay2
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cypressCache'

stages:
  - install
  - test
  - build
  - e2e
  - docker
  - deploy
  - cleanup

install:
  stage: install
  script: yarn --frozen-lockfile
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - cypressCache/
      - node_modules/

depCheck:
  stage: test
  script: yarn depCheck
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

jest:
  stage: test
  script: yarn test:jest
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    reports:
      junit: reports/junitresults.xml
    paths:
      - reports

lint:
  stage: test
  script: yarn lint
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

tsc:
  stage: test
  script: yarn tsc
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

build:app:
  stage: build
  variables:
    NODE_ENV: production
  script: yarn build:client
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/client
      - testDist/client
  dependencies: []

build:server:
  stage: build
  variables:
    NODE_ENV: production
  script: yarn build:server
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/server
      - testDist/server
  dependencies: []

codecov:
  stage: build
  script: yarn test:codecov
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  dependencies:
    - jest

.cypress_template: &cypress
  image: cypress/browsers:node12.6.0-chrome75
  stage: e2e
  variables:
    BASE_URL: http://localhost:9042
    NODE_ENV: production
    TEST_RUN: 1
  script:
    - node testDist/server/server/index.js & npx wait-on http://localhost:9042
    - yarn e2e:ci||pkill -9 node
    - pkill -9 node
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - cypressCache
      - node_modules/
  dependencies:
    - build:app
    - build:server

cypress1:
  <<: *cypress

cypress2:
  <<: *cypress

cypress3:
  <<: *cypress

docker:server:
  services:
    - docker:dind
  image: registry.gitlab.com/marudor/deploy-helper/docker
  stage: docker
  script:
    - /build.sh "Dockerfile"
  dependencies:
    - build:server
    - build:app
  only: [master]

deploy:beta:
  stage: deploy
  image: registry.gitlab.com/marudor/deploy-helper
  variables:
    GIT_STRATEGY: none
  script:
    - /helm-upgrade.sh "bahnhofsabfahrten" "bahnhofsabfahrten-beta.yaml" "bahnhofsabfahrten-beta" "$CI_COMMIT_SHA" "marudor"
  environment:
    name: beta
  only:
    - master
  dependencies: []

deploy:prod:
  stage: deploy
  image: registry.gitlab.com/marudor/deploy-helper
  variables:
    GIT_STRATEGY: none
  script:
    - /helm-upgrade.sh "bahnhofsabfahrten" "bahnhofsabfahrten.yaml" "bahnhofsabfahrten" "$CI_COMMIT_SHA" "marudor"
  environment:
    name: production
  when: manual
  only:
    - master
  dependencies: []

cleanup:
  stage: cleanup
  image: registry.gitlab.com/marudor/deploy-helper
  variables:
    GIT_STRATEGY: none
  script:
    - /cleanup.sh "marudor"
  dependencies: []
  only: [master]
