image: node:10-alpine

variables:
  DOCKER_DRIVER: overlay2

stages:
  - install
  - test
  - build
  - docker
  - deploy
  - e2e
  - cleanup

install:
  stage: install
  script: yarn --frozen-lockfile
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

depCheck:
  stage: test
  script: yarn depCheck
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

jest:
  stage: test
  script: yarn test:jest
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    reports:
      junit: reports/junitresults.xml
    paths:
      - reports


lint:
  stage: test
  script: yarn lint
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/


tsc:
  stage: test
  script: yarn tsc
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/


build:app:
  stage: build
  variables:
    NODE_ENV: production
  script: yarn build:client
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/client
  dependencies: []

build:server:
  stage: build
  variables:
    NODE_ENV: production
  script: yarn build:server
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist/server
  dependencies: []

codecov:
  stage: build
  script: yarn test:codecov
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  dependencies:
    - jest


docker:server:
  services:
    - docker:dind
  image: registry.gitlab.com/marudor/deploy-helper/docker
  stage: docker
  script:
    - /build.sh "Dockerfile"
  dependencies:
    - build:server
    - build:app
  only: [master]

deploy:beta:
  stage: deploy
  image: registry.gitlab.com/marudor/deploy-helper
  variables:
    GIT_STRATEGY: none
  script:
    - /helm-upgrade.sh "bahnhofsabfahrten" "bahnhofsabfahrten-beta.yaml" "bahnhofsabfahrten-beta" "$CI_COMMIT_SHA" "marudor"
  environment:
    name: beta
  only:
    - master
  dependencies: []

testcafe:
  image: node:10
  stage: e2e
  script:
    - yarn e2e:browserstack
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  dependencies: []
  only: [master]

deploy:prod:
  stage: deploy
  image: registry.gitlab.com/marudor/deploy-helper
  variables:
    GIT_STRATEGY: none
  script:
    - /helm-upgrade.sh "bahnhofsabfahrten" "bahnhofsabfahrten.yaml" "bahnhofsabfahrten" "$CI_COMMIT_SHA" "marudor"
  environment:
    name: production
  when: manual
  only:
    - master
  dependencies: []

cleanup:
  stage: cleanup
  image: registry.gitlab.com/marudor/deploy-helper
  variables:
    GIT_STRATEGY: none
  script:
    - /cleanup.sh "marudor"
  dependencies: []
  only: [master]
