image: node:10-alpine

variables:
  DOCKER_DRIVER: overlay2

stages:
  - install
  - test
  - build
  - docker
  - deploy
  - cleanup

install:
  stage: install
  script: yarn --frozen-lockfile
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

test:server:
  stage: test
  script: yarn test:server
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    reports:
      junit: reports/junitresults.xml
    paths:
      - reports

test:client:
  stage: test
  script: yarn test:client
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    reports:
      junit: reports/junitresults.xml
    paths:
      - reports

lint:
  stage: test
  script: yarn lint
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

flow:
  image: node:10
  stage: test
  script: yarn flow
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/

build:app:
  stage: build
  variables:
    NODE_ENV: production
  script: yarn build:client
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist
  dependencies: []

build:server:
  stage: build
  variables:
    NODE_ENV: production
  script: yarn build:server
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  artifacts:
    paths:
      - dist
  dependencies: []

codecov:
  stage: build
  script: yarn test:codecov
  cache:
    policy: pull
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  dependencies:
    - test:client
    - test:server

docker:app:
  services:
    - docker:dind
  image: registry.gitlab.com/marudor/deploy-helper/docker
  stage: docker
  script:
    - /build.sh "docker/Dockerfile.client" "/client"
  dependencies:
    - build:app

docker:server:
  services:
    - docker:dind
  image: registry.gitlab.com/marudor/deploy-helper/docker
  stage: docker
  script:
    - /build.sh "docker/Dockerfile.server" "/server"
  dependencies:
    - build:server

deploy:beta:
  stage: deploy
  image: registry.gitlab.com/marudor/deploy-helper
  script:
    - /deploy.sh "bahnhofsabfahrten-beta" "$CI_COMMIT_SHA" "marudor" "/client"
    - /deploy.sh "bahnhofsabfahrtenserver-beta" "$CI_COMMIT_SHA" "marudor" "/server"
  environment:
    name: beta
  only:
    - master
  dependencies: []

deploy:prod:
  stage: deploy
  image: registry.gitlab.com/marudor/deploy-helper
  script:
    - /deploy.sh "bahnhofsabfahrten" "$CI_COMMIT_SHA" "marudor" "/client"
    - /deploy.sh "bahnhofsabfahrtenserver" "$CI_COMMIT_SHA" "marudor" "/server"
  environment:
    name: production
  when: manual
  only:
    - master
  dependencies: []

cleanup:
  stage: cleanup
  image: registry.gitlab.com/marudor/deploy-helper
  script:
    - /cleanup.sh "marudor" /server
    - /cleanup.sh "marudor" /client
  dependencies: []
