{{- if .Values.certificate.enabled -}}
{{- $fullName := include "bahnhofsAbfahrten.fullname" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
    helm.sh/chart: {{ include "bahnhofsAbfahrten.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ $fullName }}
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
    kind: {{ .Values.certificate.issuerKind }}
  {{ if .Values.hostName }}
  dnsNames:
    - {{ .Values.hostName }}
    - www.{{ .Values.hostName }}
    {{ if .Values.docs }}
    - docs.{{ .Values.hostName }}
    - www.docs.{{ .Values.hostName }}
    {{ end }}
  {{ else }}
  dnsNames:
    - {{ .Release.Name }}.marudor.de
    - www.{{ .Release.Name }}.marudor.de
    {{ if .Values.docs }}
    - docs.{{ .Release.Name }}.marudor.de
    - www.docs.{{ .Release.Name }}.marudor.de
    {{ end }}
  {{ end }}
{{- end }}
