apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bahnhofsAbfahrten.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
    helm.sh/chart: {{ include "bahnhofsAbfahrten.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          readinessProbe:
            httpGet:
              path: /ping
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            {{ if .Values.redis.host }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            {{ end }}
            - name: BASE_URL
            {{ if .Values.hostName }}
              value: {{ .Values.hostName }}
            {{ else }}
              value: {{ .Release.Name }}.marudor.de
            {{ end }}
{{ if .Values.baseEnv }}
{{ toYaml .Values.baseEnv | indent 12 }}
{{ end }}
{{ if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
{{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
