apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-{{ include "bahnhofsAbfahrten.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
    helm.sh/chart: {{ include "bahnhofsAbfahrten.chart" . }}
    app.kubernetes.io/instance: docs-{{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
      app.kubernetes.io/instance: docs-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
        app.kubernetes.io/instance: docs-{{ .Release.Name }}
    spec:
      containers:
        - name: "docs-{{ .Chart.Name }}"
          image: redocly/redoc
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: SPEC_URL
              value: /swagger.json
            - name: PAGE_TITLE
              value: "{{ .Values.hostName }} API documentation"
