{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bahnhofsAbfahrten.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "bahnhofsAbfahrten.name" . }}
    helm.sh/chart: {{ include "bahnhofsAbfahrten.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/from-to-www-redirect: true
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
      {{ if .Values.hostName }}
        - {{ .Values.hostName }}
        {{ if .Values.docs }}
        - docs.{{ .Values.hostName }}
        {{ end }}
      {{ else }}
        - {{ .Release.Name }}.marudor.de
        {{ if .Values.docs }}
        - docs.{{ .Release.Name }}.marudor.de
        {{ end }}
      {{ end }}
      secretName: {{ $fullName }}
  rules:
    {{ if .Values.hostName }}
    - host: {{ .Values.hostName }}
    {{ else }}
    - host: {{ .Release.Name }}.marudor.de
    {{ end }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{ if .Values.docs }}
    {{ if .Values.hostName }}
    - host: docs.{{ .Values.hostName }}
    {{ else }}
    - host: docs.{{ .Release.Name }}.marudor.de
    {{ end }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: docs-{{ $fullName }}
                port:
                  number: 80
          - path: /swagger.json
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
    {{ end }}
{{- end }}
