apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bahn-expert.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bahn-expert.name" . }}
    helm.sh/chart: {{ include "bahn-expert.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bahn-expert.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: {{ include "bahn-expert.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 2
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.imageRepository }}:{{ .Values.imageTag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          readinessProbe:
            httpGet:
              path: /ping
              port: 9000
            initialDelaySeconds: 3
            periodSeconds: 3
{{ if .Values.envFrom }}
          envFrom:
{{ toYaml .Values.envFrom | indent 12 }}
{{ end }}
          env:
            - name: BASE_URL
              value: {{ .Values.hostName }}
{{ if .Values.baseEnv }}
{{ toYaml .Values.baseEnv | indent 12 }}
{{ end }}
{{ if .Values.env }}
{{ toYaml .Values.env | indent 12 }}
{{ end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{ end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
