env:
  - name: ENVIRONMENT
    value: production
  - name: LOGGLY_TOKEN
    valueFrom:
      secretKeyRef:
        name: bahnhofs-abfahrten-config
        key: loggly_token
        optional: true
  - name: PLAUSIBLE_URL
    value: https://marudor.de/api/event

hostName: marudor.de

replicaCount: 2
